/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get API version information
     * @description Retrieves API version
     */
    get: operations["getVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/access": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get HTTP API access over Wi-Fi configuration
     * @description Get HTTP API access over Wi-Fi configuration
     */
    get: operations["getHttpAccess"];
    put?: never;
    /**
     * Set HTTP API access over Wi-Fi configuration
     * @description Set HTTP API access over Wi-Fi configuration
     */
    post: operations["setHttpAccess"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current device name
     * @description Get current device name
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Information retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["NameInfo"];
          };
        };
      };
    };
    put?: never;
    /**
     * Set new device name
     * @description Set new device name
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NameInfo"];
        };
      };
      responses: {
        /** @description New name successfully set */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
        /** @description Invalid name parameter, or failed to store new name */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update firmware
     * @description Uploads a firmware update package (TAR file) and initiates the update process.
     */
    post: operations["updateFirmware"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start firmware update check
     * @description Initiates an asynchronous check for available firmware updates.
     */
    post: operations["checkFirmwareUpdate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get firmware update status
     * @description Returns current update and check status including progress information.
     */
    get: operations["getFirmwareUpdateStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get update changelog
     * @description Returns the changelog for a specific firmware version.
     */
    get: operations["getUpdateChangelog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Install firmware update
     * @description Starts asynchronous firmware installation from a remote URL.
     *     The update process (download, SHA verification, unpack, prepare, reboot) runs in the background.
     *     Use /update/status to monitor progress.
     */
    post: operations["installFirmwareUpdate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/update/abort_download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Abort ongoing firmware download
     * @description Signals the updater to abort an ongoing download operation.
     */
    post: operations["abortFirmwareDownload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/assets/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload asset file with app ID
     * @description Uploads a file to a specific app's assets directory
     */
    post: operations["uploadAssetWithAppId"];
    /**
     * Delete app assets
     * @description Deletes all assets for a specific app ID
     */
    delete: operations["deleteAppAssets"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/write": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload file to internal storage
     * @description Uploads a file to a specified path
     */
    post: operations["writeStorageFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download file from internal storage
     * @description Downloads a file from a specified path
     */
    get: operations["readStorageFile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List files on internal storage */
    get: operations["listStorageFiles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove a file on internal storage
     * @description Removes a file with a specified path
     */
    delete: operations["removeStorageFile"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/mkdir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a directory on internal storage
     * @description Creates a new directory with a specified path
     */
    post: operations["createStorageDir"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Show storage usage */
    get: operations["getStorageStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/display/draw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Draw on display
     * @description Sends drawing data to the display.
     *     Supports JSON-defined display elements.
     */
    post: operations["drawOnDisplay"];
    /**
     * Clear display
     * @description Clears the display and stops the Canvas application if running
     */
    delete: operations["clearDisplay"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/display/brightness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get display brightness
     * @description Get brightness value for displays
     */
    get: operations["getDisplayBrightness"];
    put?: never;
    /**
     * Set display brightness
     * @description Set brightness for one or both displays
     */
    post: operations["setDisplayBrightness"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audio/play": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Play audio file
     * @description Plays an audio file from the assets directory.
     *     Supported formats include .snd files.
     */
    post: operations["playAudio"];
    /**
     * Stop audio playback
     * @description Stops any currently playing audio
     */
    delete: operations["stopAudio"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audio/volume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get audio volume
     * @description Get audio volume value
     */
    get: operations["getAudioVolume"];
    put?: never;
    /**
     * Set audio volume
     * @description Set audio volume value
     */
    post: operations["setAudioVolume"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/input": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Input events streaming
     * @description Start WebSocket session for input events streaming
     */
    get: operations["connectInputWebSocket"];
    put?: never;
    /**
     * Send input event
     * @description Send single key press event
     */
    post: operations["setInputKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get device status
     * @description Get device status
     */
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/status/system": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get system status
     * @description Get system status
     */
    get: operations["getStatusSystem"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/status/power": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get power status
     * @description Get power status
     */
    get: operations["getStatusPower"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wifi/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Returns current Wi-Fi status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["StatusResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wifi/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Attempts to connect to Wi-Fi using config */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConnectRequestConfig"];
        };
      };
      responses: {
        /** @description Network connection established */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
        /** @description Already connected */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wifi/disconnect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Disconnects from Wi-Fi */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Network connection terminated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
        /** @description Already disconnected */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wifi/networks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Scans environment for available Wi-Fi networks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["NetworkResponse"];
          };
        };
        /** @description Scan not possible when connected */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/screen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get single frame for requested screen */
    get: {
      parameters: {
        query: {
          /**
           * @description Type of the display Front = 0, Back = 1
           * @example 0
           */
          display: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "image/bmp": components["schemas"]["ScreenResponse"];
          };
        };
        /** @description Wrong display */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/screen/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Screen streaming WebSocket endpoint
     * @description WebSocket connection for real-time screen streaming.
     *     Upgrade from HTTP to WebSocket protocol is required.
     *     After connection, client must send desired display ID
     *     as JSON {"display": 0}
     */
    get: operations["connectWebSocket"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ble/enable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enable BLE
     * @description Enables BLE module and starts advertising
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description BLE enabled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ble/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Disable BLE
     * @description Stops advertising
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description BLE disabled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ble/pairing": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove pairing
     * @description Remove pairing with previous device
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Pairing removed, now device is discoverable */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
        /** @description Failed to remove because BLE is not initialized or pairing was already removed */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ble/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Returns current BLE status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BleStatusResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/time": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current timestamp with timezone
     * @description Retrieves the current timestamp from RTC with timezone in ISO 8601 format
     */
    get: operations["getTime"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Unlink device from account
     * @description Removes account linking data
     */
    delete: operations["unlinkAccount"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link device to account
     * @description Requests account link PIN. Works only if device is connected to MQTT and is not linked to account
     */
    post: operations["linkAccount"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get linked account info
     * @description Retrieves linked account data
     */
    get: operations["getAccountInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get MQTT status info
     * @description Retrieves MQTT status
     */
    get: operations["getAccountState"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get MQTT profile
     * @description Retrieves MQTT backend type (dev/prod/local)
     */
    get: operations["getAccountProfile"];
    put?: never;
    /**
     * Set MQTT profile
     * @description Sets MQTT backend type (dev/prod/local)
     */
    post: operations["setAccountProfile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/time/timestamp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set current timestamp
     * @description Sets the RTC timestamp in ISO 8601 format. Time zone qualifier (e.g. Z of UTC or +hh:mm for local time) is required.
     */
    post: operations["setTimeTimestamp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/time/timezone": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get timezone
     * @description Get current timezone name
     */
    get: operations["getTimeTimezone"];
    put?: never;
    /**
     * Set timezone
     * @description Sets the timezone name. Use /time/tzlist to get available names list.
     */
    post: operations["setTimeTimezone"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/time/tzlist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get list of supported time zones
     * @description Retrieves the list of time zones accepted by /time/timezone
     */
    get: operations["getTimeTzlist"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/busy/snapshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get BUSY timer snapshot
     * @description Gets the current state of the BUSY timer in snapshot form
     */
    get: operations["getBusySnapshot"];
    /**
     * Set BUSY time snapshot
     * @description Run the timer starting from the given snapshot
     */
    put: operations["setBusySnapshot"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/matter/commissioning": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Smart home commissioning status */
    get: operations["getMatterCommissioningStatus"];
    put?: never;
    /** Link device to a smart home */
    post: operations["startMatterCommissioning"];
    /** Erase all smart home links */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully erased all Matter commissioning info, device restart is needed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SuccessResponse"];
          };
        };
        /** @description Internal Matter service is broken */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SuccessResponse: {
      /**
       * @description Success status message
       * @example OK
       */
      result: string;
    };
    /**
     * @example {
     *       "error": "Invalid parameter",
     *       "code": 400
     *     }
     */
    Error: {
      /** @description Error message */
      error: string;
      /** @description Error code */
      code?: number;
    };
    /**
     * @example {
     *       "api_semver": "0.0.0"
     *     }
     */
    VersionInfo: {
      /**
       * @description API SemVer
       * @example 0.0.0
       */
      api_semver: string;
    };
    /**
     * @example {
     *       "install": {
     *         "is_allowed": true,
     *         "event": "none",
     *         "action": "none",
     *         "status": "ok",
     *         "detail": "",
     *         "download": {
     *           "speed_bytes_per_sec": 0,
     *           "received_bytes": 0,
     *           "total_bytes": 0
     *         }
     *       },
     *       "check": {
     *         "available_version": "1.2.3",
     *         "event": "stop",
     *         "result": "available"
     *       }
     *     }
     */
    UpdateStatus: {
      install?: {
        /** @description Whether update installation is allowed (battery check) */
        is_allowed?: boolean;
        /**
         * @description Current update event
         * @enum {string}
         */
        event?:
          | "session_start"
          | "session_stop"
          | "action_begin"
          | "action_done"
          | "detail_change"
          | "action_progress"
          | "none";
        /**
         * @description Current update action
         * @enum {string}
         */
        action?:
          | "download"
          | "sha_verification"
          | "unpack"
          | "prepare"
          | "apply"
          | "none";
        /**
         * @description Current or last operation status
         * @enum {string}
         */
        status?:
          | "ok"
          | "battery_low"
          | "busy"
          | "download_failure"
          | "download_abort"
          | "sha_mismatch"
          | "unpack_staging_dir_failure"
          | "unpack_archive_open_failure"
          | "unpack_archive_unpack_failure"
          | "install_manifest_not_found"
          | "install_manifest_invalid"
          | "install_session_config_failure"
          | "install_pointer_setup_failure"
          | "unknown_failure";
        /** @description Optional status detail string */
        detail?: string;
        download?: {
          /** @description Current download speed in bytes per second */
          speed_bytes_per_sec?: number;
          /** @description Bytes received so far */
          received_bytes?: number;
          /** @description Total download size in bytes */
          total_bytes?: number;
        };
      };
      check?: {
        /** @description Version of available update (empty if none) */
        available_version?: string;
        /**
         * @description Current check event
         * @enum {string}
         */
        event?: "start" | "stop" | "none";
        /**
         * @description Check result status
         * @enum {string}
         */
        result?: "available" | "not_available" | "failure" | "none";
      };
    };
    /**
     * @example {
     *       "name": "BUSY bar"
     *     }
     */
    NameInfo: {
      /**
       * @description Device name
       * @example BUSY bar
       */
      name: string;
    };
    HttpAccessInfo: {
      /**
       * @description Access mode
       * @example key
       * @enum {string}
       */
      mode?: "disabled" | "enabled" | "key";
      /**
       * @description Access key was set and is valid
       * @example true
       */
      key_valid?: boolean;
    };
    /**
     * @example {
     *       "list": [
     *         {
     *           "type": "file",
     *           "name": "test.png",
     *           "size": 65535
     *         },
     *         {
     *           "type": "dir",
     *           "name": "assets"
     *         }
     *       ]
     *     }
     */
    StorageList: {
      /** @description Array of elements to display */
      list: components["schemas"]["StorageListElement"][];
    };
    StorageStatus: {
      /** @example 123456 */
      used_bytes?: number;
      /** @example 654321 */
      free_bytes?: number;
      /**
       * @description Total size of the partition
       * @example 777777
       */
      total_bytes?: number;
    };
    StorageListElement: {
      /**
       * @description Element type
       * @enum {string}
       */
      type: "file" | "dir";
      /** @description File or directory name */
      name: string;
    };
    StorageFileElement: Omit<
      components["schemas"]["StorageListElement"],
      "type"
    > & {
      /** @description File size in bytes */
      size: number;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "file";
    };
    StorageDirElement: Omit<
      components["schemas"]["StorageListElement"],
      "type"
    > &
      Record<string, never> & {
        /**
         * @description discriminator enum property added by openapi-typescript
         * @enum {string}
         */
        type: "dir";
      };
    /**
     * Format: binary
     * @description Binary data upload
     */
    BinaryUpload: string;
    FileUpload: {
      /**
       * Format: binary
       * @description File to upload
       */
      file: string;
    };
    /**
     * @example {
     *       "app_id": "my_app",
     *       "elements": [
     *         {
     *           "id": "0",
     *           "timeout": 10,
     *           "align": "center",
     *           "x": 36,
     *           "y": 10,
     *           "type": "text",
     *           "text": "Hello, World! Long text",
     *           "font": "medium",
     *           "color": "#FFFFFFFF",
     *           "width": 72,
     *           "scroll_rate": 1000,
     *           "display": "front"
     *         },
     *         {
     *           "id": "1",
     *           "timeout": 6,
     *           "align": "top_mid",
     *           "x": 36,
     *           "y": 0,
     *           "type": "text",
     *           "text": "top_mid",
     *           "font": "small",
     *           "color": "#AAFF00FF",
     *           "display": "front"
     *         },
     *         {
     *           "id": "2",
     *           "timeout": 6,
     *           "type": "image",
     *           "path": "data.png",
     *           "x": 0,
     *           "y": 0,
     *           "display": "back"
     *         }
     *       ]
     *     }
     */
    DisplayElements: {
      /**
       * @description Application ID for organizing assets
       * @example my_app
       */
      app_id: string;
      /** @description Array of elements to display */
      elements: components["schemas"]["DisplayElement"][];
    };
    DisplayElement: {
      /** @description Unique identifier for the element */
      id: string;
      /** @description Time in seconds the element should be displayed (0 for no timeout). Mutually exclusive with display_until. */
      timeout?: number;
      /** @description The element will be hidden when system time reaches the specified Unix timestamp (in seconds). Mutually exclusive with timeout. */
      display_until?: string;
      /**
       * @description Type of display element
       * @enum {string}
       */
      type: "text" | "image" | "anim" | "countdown";
      /** @description X coordinate of selected anchor point relative to top-left of display */
      x?: number;
      /** @description Y coordinate of selected anchor point relative to top-left of display */
      y?: number;
      /**
       * @description Which display to show the element on (for dual-display devices)
       * @default front
       * @enum {string}
       */
      display: "front" | "back";
      /**
       * @description Anchor point of element. Also use `x` and `y` to position element.
       * @enum {string}
       */
      align?:
        | "top_left"
        | "top_mid"
        | "top_right"
        | "mid_left"
        | "center"
        | "mid_right"
        | "bottom_left"
        | "bottom_mid"
        | "bottom_right";
    };
    TextElement: Omit<components["schemas"]["DisplayElement"], "type"> & {
      /** @description Text content to display */
      text: string;
      /**
       * @description One of the available fonts to display the text in
       * @default tiny5_8
       * @enum {string}
       */
      font: "small" | "medium" | "medium_condensed" | "big";
      /**
       * @description Color to display the text in, in #RRGGBBAA format
       * @default #FFFFFFFF
       */
      color: string;
      /** @description Width of the label */
      width?: number;
      /** @description Scroll rate in pixels per minute */
      scroll_rate?: number;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "text";
    };
    ImageElement: Omit<components["schemas"]["DisplayElement"], "type"> &
      (
        | {
            /** @description Path to the image file in the app's assets */
            path?: string;
          }
        | {
            /** @description Identifier of builtin image */
            builtin_image?: string;
          }
      ) & {
        /**
         * @description discriminator enum property added by openapi-typescript
         * @enum {string}
         */
        type: "image";
      };
    AnimElement: Omit<components["schemas"]["DisplayElement"], "type"> &
      ((
        | {
            /** @description Path to the animation file in the app's assets */
            path?: string;
          }
        | {
            /** @description Identifier of builtin animation */
            builtin_anim?: string;
          }
      ) & {
        /**
         * @description Whether to loop the requested part of the animation
         * @default false
         */
        loop: boolean;
        /**
         * @description If the element has been created before and this flag is true, the previous range will finish before the requested one starts.
         * @default false
         */
        await_previous_end: boolean;
        /** @description Name of the section to play back. Specifying \"default\" selects the entire animation. */
        section_name?: string;
      }) & {
        /**
         * @description discriminator enum property added by openapi-typescript
         * @enum {string}
         */
        type: "anim";
      };
    CountdownElement: Omit<components["schemas"]["DisplayElement"], "type"> & {
      /** @description Seconds-based Unix UTC timestamp to count down or up to. Note: it's a number in a string. */
      timestamp: string;
      /**
       * @description Color to display the text in, in #RRGGBBAA format
       * @default #FFFFFFFF
       */
      color: string;
      /**
       * @description Whether to count up or down
       * @enum {string}
       */
      direction: "time_left" | "time_since";
      /**
       * @description When to show the hours position
       * @enum {string}
       */
      show_hours: "when_non_zero" | "always";
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "countdown";
    };
    DisplayBrightnessInfo: {
      /**
       * @description Front display brightness (0-100/auto)
       * @example auto
       */
      front?: string;
      /**
       * @description Back display brightness (0-100/auto)
       * @example 50
       */
      back?: string;
    };
    AudioVolumeInfo: {
      /**
       * @description Audio volume value (0-100)
       * @example 50
       */
      volume?: number;
    };
    TimestampInfo: {
      /**
       * @description ISO 8601 formatted timestamp with timezone
       * @example 2025-10-02T14:30:45+04:00
       */
      timestamp: string;
    };
    TimezoneInfo: {
      /**
       * @description Timezone name
       * @example Berlin
       */
      timezone: string;
    };
    Status: {
      system?: components["schemas"]["StatusSystem"];
      power?: components["schemas"]["StatusPower"];
    };
    StatusSystem: {
      /**
       * @description Git branch name
       * @example main
       */
      branch?: string;
      /**
       * @description Firmware version
       * @example 1.0.0
       */
      version?: string;
      /**
       * @description Build date
       * @example 2024-01-01
       */
      build_date?: string;
      /**
       * @description Git commit hash (may include -dirty suffix)
       * @example abc123def456-dirty
       */
      commit_hash?: string;
      /**
       * @description System uptime
       * @example 00d 00h 04m 13s
       */
      uptime?: string;
    };
    StatusPower: {
      /**
       * @description Power state
       * @example discharging
       * @enum {string}
       */
      state?: "discharging" | "charging" | "charged";
      /**
       * @description Battery charge percent
       * @example 99
       */
      battery_charge?: number;
      /**
       * @description Battery voltage in mV
       * @example 4183
       */
      battery_voltage?: number;
      /**
       * @description Battery current in mA
       * @example -180
       */
      battery_current?: number;
      /**
       * @description USB voltage in mV
       * @example 4843
       */
      usb_voltage?: number;
    };
    /**
     * @example WPA3
     * @enum {string}
     */
    WifiSecurityMethod:
      | "Open"
      | "WPA"
      | "WPA2"
      | "WEP"
      | "WPA/WPA2"
      | "WPA3"
      | "WPA2/WPA3";
    /**
     * @example dhcp
     * @enum {string}
     */
    WifiIpMethod: "dhcp" | "static";
    /**
     * @example ipv4
     * @enum {string}
     */
    WifiIpType: "ipv4" | "ipv6";
    Network: {
      /** @example 42 */
      ssid?: string;
      security?: components["schemas"]["WifiSecurityMethod"];
      /** @example 58 */
      rssi?: number;
    };
    StatusResponse: {
      /**
       * @example disconnected
       * @enum {string}
       */
      state?:
        | "unknown"
        | "disconnected"
        | "connected"
        | "connecting"
        | "disconnecting"
        | "reconnecting";
      /** @example Your_WIFI_SSID */
      ssid?: string;
      /** @example EC:5A:00:0B:55:1D */
      bssid?: string;
      /** @example 3 */
      channel?: number;
      /** @example -43 */
      rssi?: number;
      security?: components["schemas"]["WifiSecurityMethod"];
      ip_config?: {
        ip_method?: components["schemas"]["WifiIpMethod"];
        ip_type?: components["schemas"]["WifiIpType"];
        /** @example 192.168.50.5 */
        address?: string;
      };
    };
    ConnectRequestConfig: {
      /** @example Your_WIFI_SSID */
      ssid?: string;
      /** @example Your_WIFI_Pass */
      password?: string;
      security?: components["schemas"]["WifiSecurityMethod"];
      ip_config?: {
        ip_method?: components["schemas"]["WifiIpMethod"];
        /** @example 192.168.50.5 */
        address?: string;
        /** @example 255.255.255.0 */
        mask?: string;
        /** @example 192.168.50.1 */
        gateway?: string;
      };
    };
    NetworkResponse: {
      /** @example 1 */
      count?: number;
      networks?: components["schemas"]["Network"][];
    };
    /**
     * Format: base64
     * @description Frame for requested display encoded in base64
     */
    ScreenResponse: string;
    AccountInfo: {
      /** @example true */
      linked?: boolean;
      /** @example 12345678-9abc-def0-1234-56789abcdef0 */
      id?: string;
      /** @example name@example.com */
      email?: string;
      /** @example 12345678-9abc-def0-1234-56789abcdef0 */
      user_id?: string;
    };
    AccountState: {
      /**
       * @example connected
       * @enum {string}
       */
      state?: "error" | "disconnected" | "connected";
    };
    AccountProfile: {
      /**
       * @example dev
       * @enum {string}
       */
      state?: "dev" | "prod" | "local" | "custom";
      /** @example mqtts://mqtt.example.com:8883 */
      custom_url?: string;
    };
    AccountLink: {
      /** @example ABCD */
      code?: string;
      /** @example 1761060863 */
      expires_at?: number;
    };
    BleStatusResponse: {
      /**
       * @example connected
       * @enum {string}
       */
      state?:
        | "reset"
        | "initialization"
        | "disabled"
        | "enabled"
        | "connected"
        | "internal error";
      /** @example 50:DA:D6:FE:DD:A9 */
      address?: string;
      /**
       * @example paired
       * @enum {string}
       */
      pairing?: "unknown" | "not paired" | "paired";
    };
    BusySnapshot: {
      snapshot:
        | components["schemas"]["BusySnapshotNotStarted"]
        | components["schemas"]["BusySnapshotInfinite"]
        | components["schemas"]["BusySnapshotSimple"]
        | components["schemas"]["BusySnapshotInterval"];
      /** @example 1761582532251 */
      snapshot_timestamp_ms: number;
    };
    BusySnapshotNotStarted: {
      /**
       * @example NOT_STARTED
       * @enum {string}
       */
      type: "NOT_STARTED";
    };
    BusySnapshotInfinite: {
      /**
       * @example INFINITE
       * @enum {string}
       */
      type: "INFINITE";
      /** @example 00000000-0000-0000-0000-000000000000 */
      card_id: string;
      /** @example false */
      is_paused: boolean;
    };
    BusySnapshotSimple: {
      /**
       * @example SIMPLE
       * @enum {string}
       */
      type: "SIMPLE";
      /** @example 00000000-0000-0000-0000-000000000000 */
      card_id: string;
      /** @example 9000 */
      time_left_ms: number;
      /** @example false */
      is_paused: boolean;
    };
    BusySnapshotInterval: {
      /**
       * @example INTERVAL
       * @enum {string}
       */
      type: "INTERVAL";
      /** @example 00000000-0000-0000-0000-000000000000 */
      card_id: string;
      /** @example 1 */
      current_interval: number;
      /** @example 60000 */
      current_interval_time_total_ms: number;
      /** @example 42690 */
      current_interval_time_left_ms: number;
      /** @example false */
      is_paused: boolean;
      interval_settings: components["schemas"]["BusySnapshotIntervalSettings"];
    };
    BusySnapshotIntervalSettings: {
      /**
       * @example INTERVAL
       * @enum {string}
       */
      type?: "INTERVAL";
      /** @example 120000 */
      interval_work_ms?: number;
      /** @example 60000 */
      interval_rest_ms?: number;
      /** @example 3 */
      interval_work_cycles_count?: number;
      /** @example false */
      is_autostart_enabled?: boolean;
    };
    TimezoneListResponse: {
      /**
       * @description Time zone name
       * @example Bangalore
       */
      name?: string;
      /**
       * @description Time zone offset from UTC
       * @example +05:30
       */
      offset?: string;
      /**
       * @description Time zone abbreviation
       * @example IST
       */
      abbr?: string;
    }[];
    MatterCommissionedFabrics: {
      /**
       * @description Number of Matter smart homes ("fabrics") that this device is linked with ("commissioned into")
       * @example 1
       */
      fabric_count?: number;
      latest_commissioning_status?: {
        /**
         * @description Latest state of Matter smart home linking ("commissioning") process. Note: "never_started" only refers to the current power cycle of the device; this status is not recorded across reboots.
         * @example completed_successfully
         * @enum {string}
         */
        value?:
          | "never_started"
          | "started"
          | "completed_successfully"
          | "failed";
        /**
         * @description UTC Unix millisecond timestamp of latest state update. Note: it's a number in a string.
         * @example 1769436711000
         */
        timestamp?: string;
      };
    };
    MatterCommissioningPayload: {
      /**
       * @description Linking with ("commissioning into") a Matter smart home using the provided payload is possible before this UTC Unix millisecond timestamp. Note: it's a number in a string.
       * @example 1769437579000
       */
      available_until?: string;
      /**
       * @description Payload of the QR code for linking with ("commissioning into") a Matter smart home
       * @example MT:YNDA0-O913..VV7I000
       */
      qr_code?: string;
      /**
       * @description Manual code for linking with ("commissioning into") a Matter smart home
       * @example 1155-360-0377
       */
      manual_code?: string;
    };
    MatterEndpointState: {
      /**
       * @description Type of device emulated by a Matter endpoint. Currently only "switch" is implemented.
       * @example switch
       * @enum {string}
       */
      type?: "switch";
      /**
       * @description State of device emulated by a Matter endpoint. Boolean for "switch" device type.
       * @example false
       */
      state?: boolean;
      /**
       * @description For the "switch" device type, specifies the value on startup. Never sent by the server, but can be specified by the client.
       * @enum {string}
       */
      startup?: "off" | "on" | "toggle" | "last";
    };
  };
  responses: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionInfo"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getHttpAccess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpAccessInfo"];
        };
      };
    };
  };
  setHttpAccess: {
    parameters: {
      query: {
        /**
         * @description Access mode
         * @example key
         */
        mode: "disabled" | "enabled" | "key";
        /**
         * @description Access key (4-10 digits length)
         * @example 12345678
         */
        key: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  updateFirmware: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description Update initiated successfully. The device will reboot. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid parameters, invalid TAR file, or update preparation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Update package too large. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error during update process. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  checkFirmwareUpdate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Update check started successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Update check already in progress */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Failed to start update check */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getFirmwareUpdateStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Status retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateStatus"];
        };
      };
    };
  };
  getUpdateChangelog: {
    parameters: {
      query: {
        /**
         * @description Firmware version to get changelog for
         * @example 1.2.3
         */
        version: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Changelog retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @description Changelog text */
            changelog?: string;
          };
        };
      };
      /** @description Version parameter missing, update not available, or version mismatch */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  installFirmwareUpdate: {
    parameters: {
      query: {
        /**
         * @description Firmware version to install
         * @example 1.2.3
         */
        version: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Update installation started successfully in background */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Version parameter missing, update not available, or version mismatch */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Update already in progress */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Failed to start background installation */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Battery too low for update */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  abortFirmwareDownload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Abort signal sent successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  uploadAssetWithAppId: {
    parameters: {
      query: {
        /**
         * @description Application ID for organizing assets
         * @example my_app
         */
        app_id: string;
        /**
         * @description Filename for the uploaded asset
         * @example data.png
         */
        file: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description File uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid parameters or upload failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description File too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  deleteAppAssets: {
    parameters: {
      query: {
        /**
         * @description Application ID whose assets should be deleted
         * @example my_app
         */
        app_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assets deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid app_id or deletion failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  writeStorageFile: {
    parameters: {
      query: {
        /**
         * @description Path for the uploaded file
         * @example /ext/test.png
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description File uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid parameters or upload failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description File too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  readStorageFile: {
    parameters: {
      query: {
        /**
         * @description Path to the file
         * @example /ext/test.png
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File downloaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Invalid parameters or file not exists */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listStorageFiles: {
    parameters: {
      query: {
        /**
         * @description Path to the file
         * @example /ext
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory contents read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageList"];
        };
      };
      /** @description Invalid parameters or directory does not exist */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  removeStorageFile: {
    parameters: {
      query: {
        /**
         * @description Path of a file to remove
         * @example /ext/test.png
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid path or deletion failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createStorageDir: {
    parameters: {
      query: {
        /**
         * @description Path to a new directory
         * @example /ext/newdir
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory created successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid path or creation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getStorageStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Storage status queried successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageStatus"];
        };
      };
      /** @description Invalid parameters or storage doesn't exist */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  drawOnDisplay: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DisplayElements"];
      };
    };
    responses: {
      /** @description Drawing command executed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid drawing data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Display error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  clearDisplay: {
    parameters: {
      query?: {
        /**
         * @description Application identifier
         * @example my_app
         */
        app_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Display cleared successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Display error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getDisplayBrightness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DisplayBrightnessInfo"];
        };
      };
    };
  };
  setDisplayBrightness: {
    parameters: {
      query?: {
        /**
         * @description Front display brightness (0-100/auto)
         * @example auto
         */
        front?: string;
        /**
         * @description Back display brightness (0-100/auto)
         * @example 50
         */
        back?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Brightness set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  playAudio: {
    parameters: {
      query: {
        /**
         * @description Application ID for organizing assets
         * @example my_app
         */
        app_id: string;
        /**
         * @description Path to audio file within app's assets directory
         * @example data.snd
         */
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio playback started successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid file path or file not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Audio system error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  stopAudio: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio playback stopped successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Audio system error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAudioVolume: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AudioVolumeInfo"];
        };
      };
    };
  };
  setAudioVolume: {
    parameters: {
      query: {
        /**
         * @description Audio volume (0-100)
         * @example 50
         */
        volume: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Volume set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  connectInputWebSocket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket connection established */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description WebSocket upgrade failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Upgrade required */
      426: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  setInputKey: {
    parameters: {
      query: {
        /**
         * @description Key name
         * @example ok
         */
        key:
          | "up"
          | "down"
          | "ok"
          | "back"
          | "start"
          | "busy"
          | "custom"
          | "off"
          | "apps"
          | "settings";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Input event sent successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getStatusSystem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusSystem"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getStatusPower: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusPower"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  connectWebSocket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket connection established */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Exceed max clients count */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getTime: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timestamp retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimestampInfo"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  unlinkAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Done successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  linkAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountLink"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAccountInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountInfo"];
        };
      };
    };
  };
  getAccountState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountState"];
        };
      };
    };
  };
  getAccountProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountProfile"];
        };
      };
    };
  };
  setAccountProfile: {
    parameters: {
      query: {
        /** @example dev */
        profile: "dev" | "prod" | "local" | "custom";
        custom_url?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  setTimeTimestamp: {
    parameters: {
      query: {
        /**
         * @description ISO 8601 timestamp (e.g., 2025-10-02T14:30:45+02:00 for local time or 2025-10-02T14:30:45Z for UTC)
         * @example 2025-10-02T14:30:45+0100
         */
        timestamp: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timestamp set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid timestamp format or value */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getTimeTimezone: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timezone got successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimezoneInfo"];
        };
      };
      /** @description Invalid timezone offset */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  setTimeTimezone: {
    parameters: {
      query: {
        /**
         * @description Timezone name
         * @example Stuttgart
         */
        timezone: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timezone set successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Invalid timezone offset */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getTimeTzlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Got the list successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimezoneListResponse"];
        };
      };
      /** @description Error getting time zone list */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getBusySnapshot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Got snapshot successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BusySnapshot"];
        };
      };
      /** @description Error getting snapshot */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  setBusySnapshot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusySnapshot"];
      };
    };
    responses: {
      /** @description Snapshot successfully set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Error setting snapshot */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getMatterCommissioningStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully got Matter commissioning status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MatterCommissionedFabrics"];
        };
      };
    };
  };
  startMatterCommissioning: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully started Matter commissioning */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MatterCommissioningPayload"];
        };
      };
      /** @description Internal Matter service is broken */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
