/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v0/led": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get LED state
         * @description Retrieves the current LED state
         */
        get: operations["getLedState"];
        put?: never;
        /**
         * Set LED state
         * @description Sets the LED state via query parameter or JSON body
         */
        post: operations["setLedState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get firmware version information
         * @description Retrieves firmware version, branch, build date, and commit information
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload asset file with app ID
         * @description Uploads a file to a specific app's assets directory
         */
        post: operations["uploadAssetWithAppId"];
        /**
         * Delete app assets
         * @description Deletes all assets for a specific app ID
         */
        delete: operations["deleteAppAssets"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/display/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draw on display
         * @description Sends drawing data to the display.
         *     Supports JSON-defined display elements.
         *
         */
        post: operations["drawOnDisplay"];
        /**
         * Clear display
         * @description Clears the display and stops the Canvas application if running
         */
        delete: operations["clearDisplay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/audio/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play audio file
         * @description Plays an audio file from the assets directory.
         *     Supported formats include .snd files.
         *
         */
        post: operations["playAudio"];
        /**
         * Stop audio playback
         * @description Stops any currently playing audio
         */
        delete: operations["stopAudio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws_test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket test endpoint
         * @description WebSocket connection for real-time communication and testing.
         *     Upgrade from HTTP to WebSocket protocol is required.
         *
         */
        get: operations["connectWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "state": 1
         *     } */
        LedState: {
            /**
             * @description Current LED state (0 for off, 1 for on)
             * @enum {integer}
             */
            state: 0 | 1;
        };
        /** @example {
         *       "state": 1
         *     } */
        LedStateRequest: {
            /**
             * @description LED state (0 for off, 1 for on)
             * @enum {integer}
             */
            state: 0 | 1;
        };
        SuccessResponse: {
            /**
             * @description Success status message
             * @example OK
             */
            result: string;
        };
        LedStateResponse: components["schemas"]["SuccessResponse"] & {
            /**
             * @description Current LED state (0 for off, 1 for on)
             * @enum {integer}
             */
            state: 0 | 1;
        };
        /** @example {
         *       "branch": "main",
         *       "version": "1.0.0",
         *       "build_date": "2024-01-01",
         *       "commit_hash": "abc123def456"
         *     } */
        VersionInfo: {
            /**
             * @description Git branch name
             * @example main
             */
            branch: string;
            /**
             * @description Firmware version
             * @example 1.0.0
             */
            version: string;
            /**
             * @description Build date
             * @example 2024-01-01
             */
            build_date: string;
            /**
             * @description Git commit hash (may include -dirty suffix)
             * @example abc123def456-dirty
             */
            commit_hash: string;
        };
        /**
         * Format: binary
         * @description Binary data upload
         */
        BinaryUpload: string;
        FileUpload: {
            /**
             * Format: binary
             * @description File to upload
             */
            file: string;
        };
        /** @example {
         *       "error": "Invalid parameter",
         *       "code": 400
         *     } */
        Error: {
            /** @description Error message */
            error: string;
            /** @description Error code */
            code?: number;
        };
        /** @example {
         *       "app_id": "my_app",
         *       "elements": [
         *         {
         *           "id": "0",
         *           "timeout": 5,
         *           "type": "text",
         *           "text": "Hello, world!",
         *           "x": 0,
         *           "y": 0,
         *           "display": "front"
         *         },
         *         {
         *           "id": "1",
         *           "timeout": 6,
         *           "type": "image",
         *           "path": "data.png",
         *           "x": 0,
         *           "y": 0,
         *           "display": "back"
         *         }
         *       ]
         *     } */
        DisplayElements: {
            /**
             * @description Application ID for organizing assets
             * @example my_app
             */
            app_id: string;
            /** @description Array of elements to display */
            elements: components["schemas"]["DisplayElement"][];
        };
        DisplayElement: {
            /** @description Unique identifier for the element */
            id: string;
            /** @description Time in seconds the element should be displayed (0 for no timeout) */
            timeout?: number;
            /**
             * @description Type of display element
             * @enum {string}
             */
            type: "text" | "image";
            /** @description X coordinate for placement on display */
            x: number;
            /** @description Y coordinate for placement on display */
            y: number;
            /**
             * @description Which display to show the element on (for dual-display devices)
             * @default front
             * @enum {string}
             */
            display: "front" | "back";
        };
        TextElement: Omit<components["schemas"]["DisplayElement"], "type"> & {
            /** @description Text content to display */
            text: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        ImageElement: Omit<components["schemas"]["DisplayElement"], "type"> & {
            /** @description Path to the image file in the app's assets */
            path: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLedState: {
        parameters: {
            query?: {
                /** @description LED state (0 for off, 1 for on) - alternative to JSON body */
                state?: 0 | 1;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LED state retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedStateResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setLedState: {
        parameters: {
            query?: {
                /** @description LED state (0 for off, 1 for on) - alternative to JSON body */
                state?: 0 | 1;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description LED state as JSON (alternative to query parameter) */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LedStateRequest"];
            };
        };
        responses: {
            /** @description LED state set successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedStateResponse"];
                };
            };
            /** @description Invalid state parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadAssetWithAppId: {
        parameters: {
            query: {
                /**
                 * @description Application ID for organizing assets
                 * @example my_app
                 */
                app_id: string;
                /**
                 * @description Filename for the uploaded asset
                 * @example data.png
                 */
                file: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description File uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Invalid parameters or upload failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteAppAssets: {
        parameters: {
            query: {
                /**
                 * @description Application ID whose assets should be deleted
                 * @example my_app
                 */
                app_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Invalid app_id or deletion failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    drawOnDisplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayElements"];
            };
        };
        responses: {
            /** @description Drawing command executed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Invalid drawing data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Display error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    clearDisplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Display cleared successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Display error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    playAudio: {
        parameters: {
            query: {
                /**
                 * @description Application ID for organizing assets
                 * @example my_app
                 */
                app_id: string;
                /**
                 * @description Path to audio file within app's assets directory
                 * @example data.snd
                 */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio playback started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Invalid file path or file not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Audio system error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    stopAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio playback stopped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Audio system error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    connectWebSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket connection established */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WebSocket upgrade failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Upgrade required */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
